import { setGlobal } from "../../common/global/global.js";
export class Bg {
    initialized = false;
    popupClient = null;
    ztabClient = null;
    alarmHandler = null;
    themeHandler = null;
    logoutHandler = null;
    ztabHandler = null;
    basicAuthenticationHandler = null;
    vault = null;
    vaultAudit = null;
    vaultConfig = null;
    vaultFolders = null;
    vaultLogin = null;
    vaultPolicies = null;
    vaultSecrets = null;
    vaultSecretTypes = null;
    vaultSettings = null;
    neverSaveUrls = null;
    vaultSync = null;
    vaultTrash = null;
    user = null;
    zcrypt = null;
    clipboard = null;
    offscreenApi = null;
    siteFrame = null;
    cardFrame = null;
    formFrame = null;
    saveFrame = null;
    confirmFrame = null;
    updateFrame = null;
    savePassword = null;
    neverSaveChecker = null;
    passwordReset = null;
    unlockTabHandler = null;
    csUtil = null;
    oneAuthTotp = null;
    zmaps = null;
}
export const bg = new Bg();
setGlobal("bg", bg);
