import { confMain } from "../conf/provider/main.js";
import { csApiMain } from "../csApi/provider/main.js";
import { bgApiMain } from "../provider/bgApi/main.js";
import { vtMain } from "../provider/vt/main.js";
import { BgApiServer } from "./apiBg/BgApiServer.js";
import { BgEventServer } from "./apiBg/BgEventServer.js";
import { bgUtilMain } from "./bgutil/provider/main.js";
import { ExtCryptoImpl } from "./crypto/ExtCrypto.js";
import { domainMain } from "./domain/provider/main.js";
import { AddressBarHandlerImpl } from "./handlers/AddressBarHandler.js";
import { AlarmHandler } from "./handlers/AlarmHandler.js";
import { DevToolHandler as DevToolsHandler } from "./handlers/DevToolsHandler.js";
import { InactivityHandler } from "./handlers/InactivityHandler.js";
import { InstallHandlerImpl } from "./handlers/InstallHandler.js";
import { PostUnlockTaskHandlerImpl } from "./handlers/PostUnlockTaskHandler.js";
import { SidePanelHandlerImpl } from "./handlers/SidePanelHandler.js";
import { StartupHandler } from "./handlers/StartupHandler.js";
import { oauthMain } from "./oauth/provider/main.js";
import { CDNUtil } from "./other/CDNUtil.js";
import { PasswordAssessment } from "./secret/assessment/PasswordAssessment.js";
import { DbImpl } from "./provider/db/Db.js";
import { GeneratorImpl } from "./provider/generator/Generator.js";
import { VApiImpl } from "./provider/vapi/VApi.js";
import { UnlockImpl } from "./unlock/Unlock.js";
export let installHandler = null;
export let sidePanelHandler = null;
export let addressBarHandler = null;
export let postUnlockTaskHandler = null;
export let bgEventServer = null;
export let bgApiServer = null;
export let extCrypto = null;
export let unlock = null;
export let passphraseUnlock = null;
export let alarmHandler = null;
export let inactivityHandler = null;
export let db = null;
export let accountDb = null;
export let commonDb = null;
export let devToolsHandler = null;
export let generator = null;
export let vapi = null;
export let startupHandler = null;
export let cdnUtil = null;
export let passwordAssessment = null;
export function initContext() {
    vtMain();
    bgApiMain();
    confMain();
    csApiMain();
    bgUtilMain();
    domainMain();
    oauthMain();
    db = new DbImpl();
    accountDb = db.accountDb;
    commonDb = db.commonDb;
    vapi = new VApiImpl();
    alarmHandler = AlarmHandler.getInstance();
    inactivityHandler = InactivityHandler.getInstance();
    unlock = UnlockImpl.getInstance();
    passphraseUnlock = unlock.passphrase;
    installHandler = new InstallHandlerImpl();
    sidePanelHandler = new SidePanelHandlerImpl();
    addressBarHandler = new AddressBarHandlerImpl();
    postUnlockTaskHandler = new PostUnlockTaskHandlerImpl();
    bgEventServer = new BgEventServer();
    bgApiServer = new BgApiServer();
    extCrypto = new ExtCryptoImpl();
    devToolsHandler = new DevToolsHandler();
    generator = new GeneratorImpl();
    startupHandler = new StartupHandler();
    cdnUtil = new CDNUtil();
    passwordAssessment = new PasswordAssessment();
    initGlobals();
}
function initGlobals() {
    globalThis["db"] = db;
    globalThis["accountDb"] = accountDb;
    globalThis["commonDb"] = commonDb;
    globalThis["installHandler"] = installHandler;
    globalThis["sidePanelHandler"] = sidePanelHandler;
    globalThis["addressBarHandler"] = addressBarHandler;
    globalThis["postUnlockTaskHandler"] = postUnlockTaskHandler;
    globalThis["bgEventServer"] = bgEventServer;
    globalThis["extCrypto"] = extCrypto;
    globalThis["devToolsHandler"] = devToolsHandler;
    globalThis["generator"] = generator;
    globalThis["cdnUtil"] = cdnUtil;
    globalThis["vapi"] = vapi;
    globalThis["passwordAssessment"] = passwordAssessment;
}
