import { bg } from "../src/bg/bg.js";
import { BgZCrypt } from "../src/bg/crypto/BgZCrypt.js";
import { AlarmHandler } from "../src/bg/handlers/AlarmHandler.js";
import { BgBasicAuthenticationHandler } from "../src/bg/handlers/BasicAuthenticationHandler.js";
import { BgOffscreenApiImplProvider } from "../src/bg/offscreen/BgOffscreenApiImplProvider.js";
import { BgCSUtil } from "../src/bg/other/BgCSUtil.js";
import { BgClipboardImpl } from "../src/bg/provider/other/BgClipboard.js";
import { Vault } from "../src/bg/vault/Vault.js";
import { VaultLogin } from "../src/bg/vault/VaultLogin.js";
import { VaultSecretTypes } from "../src/bg/vault/VaultSecretTypes.js";
import { VaultSecrets } from "../src/bg/vault/secrets/VaultSecrets.js";
import { BgUnlockTabHandler } from "./bg_unlocktab/BgUnlockTabHandler.js";
import { BgZTabHandler } from "./bg_ztab/BgZTabHandler.js";
import { BgCardFrame } from "./browser_tab/BgCardFrame.js";
import { BgConfirmFrame } from "./browser_tab/BgConfirmFrame.js";
import { BgFormFrame } from "./browser_tab/BgFormFrame.js";
import { BgNeverSaveChecker } from "./browser_tab/BgNeverSaveChecker.js";
import { BgSaveFrame } from "./browser_tab/BgSaveFrame.js";
import { BgSavePassword } from "./browser_tab/BgSavePassword.js";
import { BgSiteFrame } from "./browser_tab/BgSiteFrame.js";
import { BgUpdateFrame } from "./browser_tab/BgUpdateFrame.js";
import { PopupClient } from "./client/PopupClient.js";
import { ZTabClient } from "./client/ZTabClient.js";
import { PasswordReset } from "./components/PasswordReset.js";
import { LogoutHandler } from "./handlers/LogoutHandler.js";
import { ThemeHandler } from "./handlers/ThemeHandler.js";
import { OneAuthTotp } from "./oneauth/oneAuthTotp.js";
import { BgVaultUser } from "./vault/BgVaultUser.js";
import { NeverSaveUrls } from "./vault/NeverSaveUrls.js";
import { VaultAudit } from "./vault/VaultAudit.js";
import { VaultConfig } from "./vault/VaultConfig.js";
import { VaultFolders } from "./vault/VaultFolders.js";
import { VaultPolicies } from "./vault/VaultPolicies.js";
import { VaultSettings } from "./vault/VaultSettings.js";
import { VaultSync } from "./vault/VaultSync.js";
import { VaultTrash } from "./vault/VaultTrash.js";
import { ZMaps } from "./zmaps/ZMaps.js";
export class Background {
    init() {
        bg.popupClient = new PopupClient();
        bg.ztabClient = new ZTabClient();
        bg.alarmHandler = new AlarmHandler();
        bg.themeHandler = new ThemeHandler();
        bg.logoutHandler = new LogoutHandler();
        bg.ztabHandler = new BgZTabHandler();
        bg.basicAuthenticationHandler = new BgBasicAuthenticationHandler();
        bg.vault = new Vault();
        bg.vaultAudit = new VaultAudit();
        bg.vaultConfig = new VaultConfig();
        bg.vaultFolders = new VaultFolders();
        bg.vaultLogin = new VaultLogin();
        bg.vaultPolicies = new VaultPolicies();
        bg.vaultSecrets = new VaultSecrets();
        bg.vaultSecretTypes = new VaultSecretTypes();
        bg.vaultSettings = new VaultSettings();
        bg.neverSaveUrls = new NeverSaveUrls();
        bg.vaultSync = new VaultSync();
        bg.vaultTrash = new VaultTrash();
        bg.user = new BgVaultUser();
        bg.zcrypt = new BgZCrypt();
        bg.clipboard = new BgClipboardImpl();
        bg.offscreenApi = BgOffscreenApiImplProvider.getInstance();
        bg.siteFrame = new BgSiteFrame();
        bg.cardFrame = new BgCardFrame();
        bg.formFrame = new BgFormFrame();
        bg.saveFrame = new BgSaveFrame();
        bg.confirmFrame = new BgConfirmFrame();
        bg.updateFrame = new BgUpdateFrame();
        bg.savePassword = new BgSavePassword();
        bg.neverSaveChecker = new BgNeverSaveChecker();
        bg.passwordReset = new PasswordReset();
        bg.unlockTabHandler = new BgUnlockTabHandler();
        bg.csUtil = new BgCSUtil();
        bg.oneAuthTotp = new OneAuthTotp();
        bg.zmaps = new ZMaps();
    }
}
